
######################################################################
#                                                                    #
#    Decision Tree From First Principles                             #
#                                                                    #
#         Coding Exercise using Graphs                               #
#                                                                    #
#      Run the following commands (uncommented!)                     #
#       to install the required packages                             #
#                                                                    #
#       challenge -complete the function to write results as a       #
#       graphviz .dot format file   see                              #
#       def toGraphVizFile(self, filename)                           #
#                                                                    #
#      The code uses a list of indexes to define sorted subsets      #
#      of rows used for the entropy- the original indexes of the data#
#      are preserved by using index values from the input file.      #
#      It is better to build the indexes in code!!                   #
#                                                                    #           
#                                                                    #
#  This is very basic code to illustrate the  algorithm         #
#  Libraries required numpy, pandas and tabulate                     #
#  Simon Tomlinson Bioinformatics Algorithms                         #
######################################################################

import numpy as np
import pandas as pd
import tabulate as tb

# This class represents a node in the final results table
# It also generates a string describing the contents for printing


class Node:

    def __init__(self, left, right, name, cases, indexes, entropy):
        self.left = left    # left node
        self.right = right  # right node
        self.name = name    # name
        self.cases = cases  # cases
        self.indexes = indexes  # indexes of elements in teach set
        self.entropy = entropy   # entropy score of the node

    def totext(self):
        strg = "name: " + str(self.name) + "\n" + "left: " + str(self.left) + " right: " + str(self.right)
        strg = strg + "\n Entropy: " + "%0.2f" % self.entropy + "\n"

        strg = strg + self.indexestotext()

        for key, value in self.cases.items():
            strg = strg+" " + key + " " + str(value)
        return strg

    def indexestotext(self):

        s = "Indexes \n["

        for x in self.indexes:
            s = s+str(x)
            s = s+","
        s = s+"]\n"
        return s

# This class defines a binary split of the data
# In this code splits (generated by the exhaustive scan for conditions)


class MySplit:
    def __init__(self):
        self.entropies = []
        self.splits = []
        self.case = ""
        self.nodesfrom = []

    def createsplit(self, e, s, c, nf):
        self.entropies = e
        self.splits = s
        self.case = c
        self.nodesfrom = nf

    def getcombinedentropy(self):
        ent = 0

        # set this so combined entropy is 1 for empty element
        if len(self.entropies) == 0:
            return 1

        for value in self.entropies:
            ent = ent + value
        return ent / len(self.entropies)

# This is small utility class used to represent a split (a vector of indexes) and the node
# From which it was generated.


class MyASplit:
    def __init__(self, split, nodefrom):
        self.split = split
        self.nodefrom = nodefrom

# This class does not of the work...


class MyDecisionTree_CART:
    def __init__(self, mydf, class_casenames, class_cases, class_column):
        self.mydata = mydf
        self.casenames = class_casenames
        self.cases = class_cases
        self.classcolumn = class_column
        self.labels = list(set(self.mydata.iloc[:, self.classcolumn]))

        self.tree = []

    def countdistinct(self, myclasses, classlabels):
        # noticed the variables passes are only used locally here

        results = {}

        for v in classlabels:
            results[v] = 0

        for i in myclasses:

            for x in classlabels:
                if x == i:
                    results[x] = results.get(x) + 1

        return results

    def buildtree(self):

        splits_table = []
        self.tree = []

        # create the first node
        count_classlabels_presplit = self.countdistinct(self.mydata.iloc[:, self.classcolumn], self.labels)

        entropy_pre = self.entropy(count_classlabels_presplit)
        print("Entropy for starting point: %d" % entropy_pre)

        # add the first node

        self.tree.append(
            Node(0, 0, "root", count_classlabels_presplit, self.mydata.iloc[:, self.classcolumn], entropy_pre))

        # OK now decide how to split the quantitative data into groups.

        err = self.mydata.iloc[:, self.casenames].values.tolist()

        bestsplit = self.buildtreelayer(MyASplit(err, 0))
        if bestsplit.getcombinedentropy() <= 0:
            print("Completed Successfully..")
            return 0
        # simple termination heuristic here
        if len(bestsplit.splits[0]) <= 2 or len(bestsplit.splits[1]) <= 2:
            print("Completed successfully.. splits too small to continue")
            return 0

        # otherwise just store the splits
        if len(bestsplit.splits[0]) > 2:
            splits_table.append(MyASplit(bestsplit.splits[0], bestsplit.nodesfrom[0]))
        if len(bestsplit.splits[1]) > 2:
            splits_table.append(MyASplit(bestsplit.splits[1], bestsplit.nodesfrom[1]))

        # add  a sanity check loop counter
        loop = 0

        while len(splits_table) > 0:

            loop += 1

            sp = splits_table.pop()

            bestsplit = self.buildtreelayer(sp)
            if bestsplit.getcombinedentropy() <= 0:
                print("Completed Successfully..")
                return 0
                # simple termination heuristic here
            if len(bestsplit.splits[0]) <= 2 or len(bestsplit.splits[1]) <= 2:
                print("Completed successfully.. splits too small to continue")
                return 0

            if loop > 0:
                print("Terminated due to insufficient time to solve the problem")
                return -1

                # otherwise just store the splits
            if len(bestsplit.splits[0]) > 2:
                splits_table.append(MyASplit(bestsplit.splits[0], bestsplit.nodesfrom[0]))
            if len(bestsplit.splits[1]) > 2:
                splits_table.append(MyASplit(bestsplit.splits[1], bestsplit.nodesfrom[1]))

        return -1

    def buildtreelayer(self, sp):

        best_split = MySplit()

        for i in self.cases:
            print("Considering case: " + self.mydata.columns[i])

            best_split2 = self.getBestSplit(sp.split, i, sp.nodefrom)
            if best_split2.getcombinedentropy() < best_split.getcombinedentropy():
                best_split = best_split2

        # Current best entropy
            print("Entropy for starting point: %.2f" % best_split.getcombinedentropy())

        # Now store this next node in the tree

        counts1 = self.countdistinct(self.mydata.iloc[best_split.splits[0], self.classcolumn], self.labels)
        counts2 = self.countdistinct(self.mydata.iloc[best_split.splits[1], self.classcolumn], self.labels)

        self.tree[sp.nodefrom].left = sp.nodefrom + 1
        self.tree[sp.nodefrom].right = sp.nodefrom + 2

        self.tree.append(Node(-1, -1, self.mydata.columns.values[best_split.case], counts1, best_split.splits[0], best_split.entropies[0]))
        # store the branches in the tree

        self.tree.append(Node(-1, -1, self.mydata.columns.values[best_split.case], counts2, best_split.splits[1], best_split.entropies[1]))
        # store the branches in the tree

        best_split.nodesfrom.clear()
        best_split.nodesfrom.append(self.tree[sp.nodefrom].left)
        best_split.nodesfrom.append(self.tree[sp.nodefrom].right)

        return best_split

    # Exhaustive partition search using rank order and a single boundary

    def getBestSplit(self, rows_to_include, casetoconsider, parentnode):

        subtable = self.mydata.iloc[rows_to_include, :]
        # print(tb.tabulate(subtable, headers='keys', tablefmt='psql'))

        sorted_indexes = subtable.iloc[:, casetoconsider]
        sorted_order = np.argsort(sorted_indexes)

        subtable = subtable.iloc[sorted_order, :]

        # print("sorted")
        # print(tb.tabulate(subtable, headers='keys', tablefmt='psql'))

        # simply store the best core here
        best_split = MySplit()

        # Now consider each possible split.
        for x in range(1, len(subtable) -1):

            # This is a slow way to do this but easy to see in code -we also only consider binary split here
            top_subtable =subtable.iloc[0: x, :]
            count_classlabels_top_subtable = self.countdistinct(top_subtable.iloc[:, self.classcolumn], self.labels)
            entropy_top = self.entropy(count_classlabels_top_subtable)

            bottom_subtable = subtable.iloc[x: len(subtable), :]
            count_classlabels_bottom_subtable = self.countdistinct(bottom_subtable.iloc[:, self.classcolumn], self.labels)
            entropy_bottom = self.entropy(count_classlabels_bottom_subtable)

            current_split = MySplit()
            current_split.splits.append(list(top_subtable.iloc[:, self.casenames]))
            current_split.splits.append(list(bottom_subtable.iloc[:, self.casenames]))

            current_split.entropies.append(entropy_top)
            current_split.entropies.append(entropy_bottom)
            current_split.case = casetoconsider
            current_split.case = parentnode

            # store the entropy results
            if current_split.getcombinedentropy() < best_split.getcombinedentropy():
                best_split = current_split
                '''
                print("New Best entropy %.2f " % best_split.getCombinedEntropy())
                print(f"Ent top {float(best_split.entropies[0]):.2}")
                print("Ent bottom %.2f" % best_split.entropies[1])
                print("Split top")
                print(best_split.splits[0])
                print("Split bottom")
                print(best_split.splits[1])
                print("Best average %.2f \n" % best_split.getCombinedEntropy())
                '''

        return best_split

    def toGraphVizFile(self, filename):

        # see https://www.graphviz.org/pdf/dotguide.pdf

        print("plot Graph in graphviz")

        '''
            digraph myexample {
            A -> B [ label = "this" ];
            B -> C [ label = "that" ];
            A [label="Node A"];
            }
      '''

    # This function just iterates the list of Nodes used to store the tree
    # Note how the leaf nodes have -1 connections.
    # Binary can be asymmetric with 0 nodes downstream (leaf nodes) or
    # They can have 1 node or 2- but no more.
    def printTreeNodes(self):
        # just print out the list of modes

        print("Printing just a list of nodes...")

        index = 0
        for nnode in self.tree:
            print("\n")
            print("Index of Node: " + str(index))
            print(nnode.totext())
            index = index + 1

    # basic entropy approach- but what if sum_elements =0
    def entropy(self, count_classlabels_asplit):
        # print("Calculating Entropy")

        # we need the total counts for each of the splits
        sum_elements = self.getSum(count_classlabels_asplit)

        # add some extra controls here to prevent div0 and othererrors
        if sum_elements <= 1:
            return 1

        ent = 0

        for key in self.labels:
            value = count_classlabels_asplit[key]

            if value <= 0:
                continue
            # Some cases ma have value =0 entropy is 0 -so we avoid NaN here
            # Numpy offers vectored numerical operations which are preferable here

            percent = value/sum_elements

            ent = ent + (percent * np.log2(percent))
        ent = ent * -1

        if ent < 0:
            ent = 0.00

        return ent

    def getSum(self, classlabs):
        ssum = 0
        for key, value in classlabs.items():
            ssum = ssum + value
        return ssum


# OK Load some data- here we use a table parser from Pandas to read the file
# Subset the data by parameters by both factors and cases

# load data as a dataframe in Python
mydf = pd.read_table("TestClassification2.txt", delimiter="\t")

# print out the table- here in psql format
print(tb.tabulate(mydf, headers='keys', tablefmt='psql'))

# set columns to use in the analysis
class_column = 4
class_cases = [1, 2, 3]
class_casenames = 0

# drive the building process
mydecisiontree = MyDecisionTree_CART(mydf, class_casenames, class_cases, class_column)
mydecisiontree.buildtree()

# seems to work OK
mydecisiontree.printTreeNodes()

# Write out the final plot in .dot format.. TODO!!
# mydecisiontree.toGraphVizFile(afilename)
